from __future__ import annotations

import collections
import re
import xml.etree.ElementTree as ET
from pathlib import Path

from editorial_overrides import EXACT_OVERRIDES as EDITORIAL_EXACT_OVERRIDES
from editorial_overrides import UID_OVERRIDES as EDITORIAL_UID_OVERRIDES
from proofreading_overrides import EXACT_OVERRIDES as PROOFREADING_EXACT_OVERRIDES
from proofreading_overrides import UID_OVERRIDES as PROOFREADING_UID_OVERRIDES
from proofreading_overrides import normalize as proofreading_normalize


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "audit_installed_20260824_2257" / "base" / "Mods" / "DnD2024_897914ef-5c96-053c-44af-0be823f895fe" / "Localization" / "English" / "english.xml"
TARGET = ROOT / "ukrainian_current.xml"
BG_EN = ROOT / "bg3-en.xml"
BG_UK = ROOT / "bg3-uk.xml"

TAG_SPLIT_RE = re.compile(r"(</?[^>]+>)")
CYRILLIC_RE = re.compile(r"[А-Яа-яІіЇїЄєҐґ]")
LATIN_RE = re.compile(r"[A-Za-z]")


UID_OVERRIDES = {
    "h3af4f15fgffa3gf824ga850g5f3edec1f758": 'Під час поєднання екстрактів ви можете приготувати два алхімічні розчини замість одного, якщо успішно пройдете <LSTag Tooltip="DifficultyClass">МС</LSTag> 15 <LSTag Type="Skills" Tooltip="Medicine">Медицина</LSTag> <LSTag Tooltip="AbilityCheck">перевірку</LSTag>.',
    "he73898ceg2342gac1agce15gffad564f5c59": 'Месник. До кінця вашого наступного ходу будь-яка істота, яка влучає в ціль атакою ближнього бою, зазнає силової шкоди, що дорівнює кидку вашої кістки <LSTag Type="ActionResource" Tooltip="BardicInspiration">Бардівського натхнення</LSTag>.',
    "h97319f1bgef21gc6f0g305bg9cc81c5b14c1": 'До кінця вашого наступного ходу будь-яка істота, яка влучає в ціль атакою ближнього бою, зазнає силової шкоди, що дорівнює кидку вашої кістки <LSTag Type="ActionResource" Tooltip="BardicInspiration">Бардівського натхнення</LSTag>.',
    "h2f5f424bg14ceg447ag33b9g312025e7738d": 'Завдає додаткової шкоди [1] зброєю ближнього бою, імпровізованою зброєю та кинутими предметами. <br><br>Союзники мають <LSTag Tooltip="Advantage">перевагу</LSTag> на <LSTag Tooltip="AttackRoll">кидки атаки</LSTag> проти ворогів у межах [2].<br><br>Також має стійкість до фізичної шкоди та перевагу на <LSTag Tooltip="AbilityCheck">перевірки</LSTag> й <LSTag Tooltip="SavingThrow">кидки протидії</LSTag> силою.<br><br>Не може проказувати закляття або підтримувати концентрацію.',
    "h708146b3g1fd7g7ca1g06e9g815f4a5e342b": 'Завдає додаткової шкоди [1] зброєю ближнього бою, імпровізованою зброєю та кинутими предметами. <br><br>Союзники мають <LSTag Tooltip="Advantage">перевагу</LSTag> на <LSTag Tooltip="AttackRoll">кидки атаки</LSTag> проти ворогів у межах [2].<br><br>Також має стійкість до фізичної шкоди та перевагу на <LSTag Tooltip="AbilityCheck">перевірки</LSTag> й <LSTag Tooltip="SavingThrow">кидки протидії</LSTag> силою.<br><br>Не може проказувати закляття або підтримувати концентрацію.',
    "hb6a93cc1gf0edgea86g2a35gf0e952666978": 'Істота додатково зазнає [1] від заклинача. Вона також має <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> сили та <LSTag Tooltip="SavingThrow">кидків протидії</LSTag> силою.',
    "h99a0b10fg027fga188g2137g2653a7759874": 'Істота додатково зазнає [1] від заклинача. Вона також має <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> спритності та <LSTag Tooltip="SavingThrow">кидків протидії</LSTag> спритністю.',
    "ha1b537d6gb014g4e76gdd96g37cbe829c37c": 'Істота додатково зазнає [1] від заклинача. Вона також має <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> статури та <LSTag Tooltip="SavingThrow">кидків протидії</LSTag> статурою.',
    "h85242573gb807g8f1eg76beg922d8d905e93": 'Істота додатково зазнає [1] від заклинача. Вона також має <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> інтелекту та <LSTag Tooltip="SavingThrow">кидків протидії</LSTag> інтелектом.',
    "h3c6667d4gfa1bgc9b9g5be0gb270c5c555d5": 'Істота додатково зазнає [1] від заклинача. Вона також має <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> мудрості та <LSTag Tooltip="SavingThrow">кидків протидії</LSTag> мудрістю.',
    "h99239365g1e0eg35cfgc2edg0a2bbfb668ae": 'Істота додатково зазнає [1] від заклинача. Вона також має <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> харизми та <LSTag Tooltip="SavingThrow">кидків протидії</LSTag> харизмою.',
    "h87d4e985gc3a3g6b66g2385g07e2b48896df": 'Ви можете використати <LSTag Type="Spell" Tooltip="Target_DeathWard">Оберіг від смерті</LSTag>, не витрачаючи <LSTag Tooltip="SpellSlot">чарунку заклять</LSTag>.',
    "hc69907d4g8c9eg708ag8797ge1e6e4d47653": 'Витратьте [1] очок чародійства, щоб розблокувати <LSTag Tooltip="SpellSlot">чарунку заклять</LSTag> [2]-го рівня. Створення іншої чарунки того самого рівня не матиме ефекту, доки не буде використана ця.',
    "hd2aeaec7g64f4g180fg4fc9g91918a557c3c": 'Обхід укриття. Ваші дальні атаки закляттями не зазнають штрафів від <LSTag Tooltip="HighGroundRules">правил висоти</LSTag>.\n\nПроказування в ближньому бою. Перебування в межах 5 футів від ворога не спричиняє завади для ваших кидків атаки закляттями.\n\nЗбільшена дальність. Збільшити дальність заклять на 50%.',
    "h7bd1bb01g45ccge8e6g5722g3072b6b0bf23": 'Ви перебуваєте в стані <LSTag Type="Status" Tooltip="INVISIBLE">Невидимості</LSTag> до початку свого наступного ходу або доки не виконаєте кидок атаки, не завдасте шкоди чи не прокажете закляття.',
    "h4b3bbd82gcfdegf0b2g8843g1b27f8c2a5b8": 'Коли ви надихаєте союзника за допомогою <LSTag Type="Spell" Tooltip="Target_BardicInspiration">Бардівського натхнення</LSTag>, він також відновлює [1] відповідно до результату кидка вашої кістки <LSTag Type="ActionResource" Tooltip="BardicInspiration">Бардівського натхнення</LSTag>.',
    "h4b3edb5dg700eg11d2gb46eg867808ec1738": 'Ваш досвід боротьби із заклиначами дає такі переваги.\n\nРуйнівник концентрації. Кожен ваш дальній кидок атаки розсіює захисну магію на цілі й перериває її концентрацію.\n\nАнтимагічний постріл. Коли ви завдаєте критичного влучання цілі під дією вашої особливості <LSTag Type="Status" Tooltip="GUT_SHOT">Постріл у живіт</LSTag>, ви також перешкоджаєте їй проказувати закляття. Поки снаряд залишається в цілі, вона не може проказувати закляття або виконувати магічну дію.\n\nЗагартований магією. Проваливши кидок протидії закляттю чи магічному ефекту, ви можете застосувати реагування, кинути 1d6 і додати результат, потенційно перетворивши невдачу на успіх.',
    "h848282acg476egf71fgd7feg17ed2acf814f": 'Коли ви досягаєте певних рівнів чародія, у вас завжди підготовлені певні закляття. На 3-му рівні у вас завжди підготовлені Зцілення ран, Вказівний заряд, Мале відновлення та Палюче проміння. На 5-му рівні також підготовлені Аура життєвості та Чароспин. На 7-му — Вогняний щит і Стіна вогню. На 9-му — Велике відновлення й Вогняний стовп.',
    "hd22a1ff8gaca7gd01cg610fgbe3a8ed48875": 'Починаючи з 3-го рівня, після досягнення певних рівнів цього класу у вас завжди підготовлені відповідні закляття. Вони вважаються для вас закляттями винахідника, але не враховуються до кількості заклять винахідника, які ви можете підготувати. На 3-му рівні ви отримуєте Героїзм і Щит. На 5-му — Ганебну кару та Захисний зв’язок. На 9-му — Ауру життєвості й Прикликаний обстріл.',
    "h4336900ag6e5egc73bgadb8g0a8300eeb536": 'Магія вашого покровителя гарантує, що у вас завжди підготовлені певні закляття. Досягнувши рівня чаклуна, указаного в таблиці заклять Відьомського клинка, ви завжди матимете підготовлені наведені закляття. На 3-му рівні ви вивчаєте <LSTag Type="Spell" Tooltip="Shout_ArcaneVigor">Містичну снагу</LSTag>, Прокльон, Магічну зброю, Щит і Гнівну кару. На 5-му — Накладання прокляття та Прикликаний обстріл. На 7-му — Свободу руху й Нищівну кару. На 9-му — Удар сталевого вітру.',
    "h6b8ec4b1g6350g0a0ag1d7dgc74d66ad8dd7": 'На 3-му рівні ви вивчаєте Містичну снагу, Прокльон, Магічну зброю, Щит і Гнівну кару. На 5-му — Накладання прокляття та Прикликаний обстріл. На 7-му — Свободу руху й Нищівну кару. На 9-му — Удар сталевого вітру.',
    "h6b8c9b31g95bbg4d4cga9a0gf66e4d6187f5": 'Доступні класи: бард, чародій, чаклун, чарівник',
    "hd98d7d87g77cegbc88gd214g64ac7bacec24": 'Ваш зв’язок із цим божественним доменом гарантує, що у вас завжди підготовлені певні закляття. Досягнувши рівня клірика, указаного в таблиці заклять Домену розуму, ви завжди матимете підготовлені наведені закляття. На 3-му рівні ви вивчаєте Наказ, Виявлення думок, Нерозбірливий шепіт і Прокол розуму; на 5-му — Чароспин і Страх; на 7-му — <LSTag Type="Spell" Tooltip="Target_Confusion">Збентеження</LSTag> та Примарного убивцю; на 9-му — Синаптичний розряд і Телекінез.',
    "h793cd839gb6abg5b14g2409gcd0bd8f9ce42": 'На 3-му рівні ви вивчаєте Наказ, Виявлення думок, Нерозбірливий шепіт і Прокол розуму; на 5-му — Чароспин і Страх; на 7-му — <LSTag Type="Spell" Tooltip="Target_Confusion">Збентеження</LSTag> та Примарного убивцю; на 9-му — Синаптичний розряд і Телекінез.',
}


# New 2024/mod terms which are absent from the shipped BG3 localization.
# Existing game concepts below deliberately use the official BG3 Ukrainian wording.
EXACT_OVERRIDES = {
    "Rule: One Spell with a Spell Slot per Turn": "Правило: одне закляття з чарункою заклять за хід",
    "Magic Initiate": "Магічний хист",
    "Eldritch Adept": "Потойбічний адепт",
    "Eldritch Smite": "Потойбічна кара",
    "Mind Sliver": "Уламок розуму",
    "Find Steed": "Знайти скакуна",
    "Faithful Steed": "Вірний скакун",
    "Steed Action Point": "Очко дії скакуна",
    "Dreadful Strike": "Жахливий удар",
    "Dreadful Strike (Melee)": "Жахливий удар (ближній бій)",
    "Dreadful Strike (Ranged)": "Жахливий удар (дальній бій)",
    "Improved Sneak Attack": "Покращений підступний удар",
    "Level 2: Magic Initiate (Wizard, Lessons of the First Ones)": "Рівень 2: Магічний хист (чарівник, Уроки найперших)",
    "Level 2: Magic Initiate (Cleric, Lessons of the First Ones)": "Рівень 2: Магічний хист (клірик, Уроки найперших)",
    "Level 2: Magic Initiate (Druid, Lessons of the First Ones)": "Рівень 2: Магічний хист (друїд, Уроки найперших)",
    "Roving Aim": "Рухоме прицілювання",
    "Sorcerous Restoration": "Чародійське відновлення",
    "Beguiling Magic": "Зваблива магія",
    "Beguiling Magic: Charmed": "Зваблива магія: причарування",
    "Beguiling Magic: Frightened": "Зваблива магія: переляк",
    "Circle Forms": "Подоби кола",
    "Improved Circle Form": "Покращені подоби кола",
    "Circle of the Moon Spells": "Закляття Кола місяця",
    "Circle of the Land Spells": "Закляття Кола землі",
    "Circle of the Land Spells: Arid Land": "Закляття Кола землі: посушливі землі",
    "Circle of the Land Spells: Polar Land": "Закляття Кола землі: полярні землі",
    "Circle of the Land Spells: Temperate Land": "Закляття Кола землі: помірні землі",
    "Circle of the Land Spells: Tropical Land": "Закляття Кола землі: тропічні землі",
    "College of Dance": "Колегія танцю",
    "College of the Moon": "Колегія місяця",
    "College of Spirits": "Колегія духів",
    "College of Choreography": "Колегія хореографії",
    "Path of the Zealot": "Шлях ревнителя",
    "Oath of Glory": "Обіт слави",
    "Oath of the Glory Tenets": "Засади Обіту слави",
    "Oath of Glory Spells": "Закляття Обіту слави",
    "Oath of the Noble Genies": "Обіт шляхетним джинам",
    "Oath of the Noble Genies Tenets": "Засади Обіту шляхетним джинам",
    "Oath of Conquest": "Обіт завоювання",
    "Oath of Conquest Spells": "Закляття Обіту завоювання",
    "Oath of the Watchers": "Обіт дозорців",
    "Oath of the Watchers Spells": "Закляття Обіту дозорців",
    "Grave Domain Spells": "Закляття Могильного домену",
    "Forge Domain Spells": "Закляття Домену ковальства",
    "Celestial Patron": "Небесний покровитель",
    "Undead Patron": "Невмерлий покровитель",
    "Hexblade Patron": "Покровитель-відьомський клинок",
    "Archfey Patron": "Покровитель-архіфея",
    "Fiend Patron": "Покровитель-нечистий",
    "Great Old One Patron": "Покровитель — Величний древній",
    "Circle of the Unbroken": "Коло незламних",
    "Circle of the Unbroken Spells": "Закляття Кола незламних",
    "Path of the Fractured": "Шлях розколотого",
    "Fey Wanderer": "Фейський мандрівник",
    "Soulknife": "Клинок душі",
    "Blade of Radiance": "Клинок сяйва",
    "Arachnoid Stalker": "Арахноїдний мисливець",
    "Aberrant Sorcery": "Аберантне чаклунство",
    "Spellfire Sorcery": "Чаровогняне чаклунство",
    "Wild Magic Sorcery": "Чаклунство дикої магії",
    "Abjurer": "Віднаджувач",
    "Diviner": "Ворожбит",
    "Evoker": "Втілювач",
    "Illusionist": "Ілюзіоніст",
    "High Roller": "Великий гравець",
    "Spellslinger": "Чаростріл",
    "Painkiller": "Знеболювач",
    "Sanguine Knight": "Кривавий лицар",
    "Abyssal Tiefling": "Абісальний бісин",
    "Chthonic Tiefling": "Хтонічний бісин",
    "Infernal Tiefling": "Пекельний бісин",
    "Vex": "Збентеження",
    "Glaive, Greatsword": "Глефа, дворучний меч",
    "Club, Javelin, Light Crossbow, Longbow, Musket, Whip": "Палиця, дротик, легкий арбалет, довгий лук, мушкет, батіг",
    "Quarterstaff, Battleaxe, Maul, Trident": "Бойовий посох, бойова сокира, молот, тризуб",
    "Handaxe, Shortbow, Rapier, Shortsword, Hand Crossbow, Pistol": "Ручна сокира, короткий лук, рапіра, короткий меч, ручний арбалет, пістоль",
    "Greatclub, Pike, Warhammer, Heavy Crossbow": "Велика довбня, піка, бойовий молот, важкий арбалет",
    "Divine Spark: Radiant Damage": "Божественна іскра: променева шкода",
    "Divine Spark: Necrotic Damage": "Божественна іскра: некротична шкода",
    "Reckless Attack: Forceful Blow": "Зухвала атака: силовий удар",
    "Reckless Attack: Hamstring Blow": "Зухвала атака: удар по сухожиллю",
    "Warding Flare (Self)": "Охоронний спалах (на себе)",
    "Starry Wisp": "Зоряний вогник",
    "Wild Shape Vitality": "Життєва сила Дикої подоби",
    "Heroic Warrior: Reroll Attacker's Die": "Героїчний воїн: перекинути кістку нападника",
    "Heroic Warrior: Reroll with Advantage": "Героїчний воїн: перекинути з перевагою",
    "Extra Attack 2 (Cantrip)": "Додаткова атака 2 (замовляння)",
    "Cunning Strike: Trip": "Хитрий удар: підсічка",
    "Cunning Strike: Terrify": "Хитрий удар: залякування",
    "Agile Strikes": "Спритні удари",
    "Darkness Recast": "Повторне проказування Пітьми",
    "Psionic Strike on Critical": "Псіонічний удар при критичному влучанні",
    "Heroic Inspiration: Reroll with Advantage (Attack Roll)": "Героїчне натхнення: перекинути з перевагою (кидок атаки)",
    "Heroic Inspiration: Reroll with Advantage (Saving Throw)": "Героїчне натхнення: перекинути з перевагою (кидок протидії)",
    "Eldritch Hexed: Wisdom": "Прокляття потойбіччя: мудрість",
    "Shadow Touched": "Торкнутий тінню",
    "Dragon Hide": "Драконяча шкура",
    "Fade Away": "Зникнення",
    "Origin Feat: Emerald Enclave Fledgling": "Риса походження: новак Смарагдового анклаву",
    "Origin Feat: Lords’ Alliance Agent": "Риса походження: агент Альянсу володарів",
    "Spellfire Spark": "Іскра чаровогню",
    "Mythalkeeper": "Хранитель міфалю",
    "Shadowmasters Exile": "Вигнанець Володарів тіней",
    "Spellfire Initiate": "Посвячений у чаровогонь",
    "Genie Magic": "Магія джина",
    "Hunter's Rime": "Паморозь мисливця",
    "Winter Walker": "Зимовий мандрівник",
    "Marid’s Surge": "Сплеск марида",
    "Dread Allegiance": "Грізна відданість",
    "Starry Wisp": "Зоряний вогник",
    "Prestidigitation": "Дрібні чари",
    "Agile Strikes": "Спритні удари",
    "Fade Away": "Зникнення",
    "Shadowmaster": "Володар тіней",
    "Bladessons": "Пісня клинка",
    "Bind Pact": "Скріпити пакт",
    "Umbral Killer": "Тіньовий убивця",
    "Fire’s Burn": "Опік вогню",
    "Frost’s Chill": "Холод морозу",
    "Hill’s Tumble": "Перекид пагорба",
    "Divine Points": "Божественні очки",
    "Rend the Blasphemous": "Роздерти богохульника",
    "Vitriolic Sphere": "Їдка сфера",
    "Synaptic Static": "Синаптичний розряд",
    "Dread Allegiance": "Грізна відданість",
    "Starry Wisp": "Зоряний вогник",
    "Prestidigitation": "Дрібні чари",
    "Agile Strikes": "Спритні удари",
    "Fade Away": "Зникнення",
    "Shadowmaster": "Володар тіней",
    "Genie Magic": "Магія джина",
    "Bladessons": "Пісня клинка",
    "Bind Pact": "Скріпити пакт",
    "Umbral Killer": "Тіньовий убивця",
    "Fire’s Burn": "Опік вогню",
    "Frost’s Chill": "Холод морозу",
    "Hill’s Tumble": "Перекид пагорба",
    "Divine Points": "Божественні очки",
    "Rend the Blasphemous": "Роздерти богохульника",
    "Vitriolic Sphere": "Їдка сфера",
    "Synaptic Static": "Синаптичний розряд",
    "Force Demolisher": "Силовий руйнівник",
    "Bladesinger": "Співець клинка",
    "Dread Allegiance": "Грізна відданість",
    "Dread Allegiance: Bane": "Грізна відданість: Бейн",
    "Dread Allegiance: Bhaal": "Грізна відданість: Баал",
    "Fire’s Burn": "Опік вогню",
    "Frost’s Chill": "Холод морозу",
    "Hill’s Tumble": "Перекид пагорба",
    "Bite the Bullet": "Зціпити зуби",
    "Highway Rider": "Дорожній вершник",
    "Hellspeaker": "Промовець Пекла",
    "Umbral Killer": "Тіньовий убивця",
    "Shadowmaster": "Володар тіней",
    "Vengeful Blade Damage": "Шкода Мстивого клинка",
    "Hell’s Lash": "Батіг Пекла",
    "Hell's Lash": "Батіг Пекла",
    "Spellblade": "Чароклинок",
    "Prestidigitation: Ignite": "Дрібні чари: запалити",
    "Prestidigitation: Snuff": "Дрібні чари: загасити",
    "Swift Witchcraft": "Швидке чаклування",
    "Shadow Gnawer": "Тінегриз",
    "Shadow Smoke": "Тіньовий дим",
    "Force Demolisher: Push": "Силовий руйнівник: поштовх",
    "Lightning Launcher": "Блискавкомет",
    "Force Ballista": "Силова баліста",
    "Mind Sliver (Lingering)": "Уламок розуму (тривалий)",
    "DeftStrike": "Вправний удар",
    "Close Quarters": "Ближній бій",
    "Doom Song": "Пісня приречення",
    "Doom Song Target": "Ціль Пісні приречення",
    "Hollow Warden": "Порожній вартовий",
    "Hungering Might": "Голодна міць",
    "Archfey Patron": "Покровитель-архіфея",
    "Fiend Patron": "Покровитель-нечистий",
    "Rune Shaper: Enemy": "Творець рун: ворог",
    "Rune Shaper: Journey": "Творець рун: подорож",
    "Rune Shaper: Storm": "Творець рун: буря",
    "Bigby Presents: Glory of the Giants": "Біґбі представляє: Слава велетнів",
    "Slasher: Enhanced Critical": "Рубака: посилене критичне влучання",
    "Piercer: Enhanced Critical": "Проколювач: посилене критичне влучання",
    "Devastator: Unarmed Attack": "Спустошувач: атака голіруч",
    "Spellfire Storm: Spell Disruption": "Буря чаровогню: зрив закляття",
    "Shadow Grasp": "Тіньовий захват",
    "Spirits From Beyond: Sharpshooter": "Духи з потойбіччя: снайпер",
    "Spirits From Beyond: Renegade": "Духи з потойбіччя: відступник",
    "Rend the Blasphemous": "Роздерти богохульника",
    "Trollblood Infusion": "Вливання тролячої крові",
    "Cacophonic Shield Aura": "Аура какофонічного щита",
    "Web": "Павутиння",
    "Inflict Wounds": "Завдання ран",
    'Deal an additional [1] when you attack the target and impart <LSTag Tooltip="Disadvantage">Disadvantage</LSTag> on Strength <LSTag Tooltip="AbilityCheck">Checks</LSTag>.': 'Завдайте додаткової [1] під час атаки цілі й надайте їй <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> сили.',
    'Deal an additional [1] when you attack the target and impart <LSTag Tooltip="Disadvantage">Disadvantage</LSTag> on Dexterity <LSTag Tooltip="AbilityCheck">Checks</LSTag>.': 'Завдайте додаткової [1] під час атаки цілі й надайте їй <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> спритності.',
    'Deal an additional [1] when you attack the target and impart <LSTag Tooltip="Disadvantage">Disadvantage</LSTag> on Constitution <LSTag Tooltip="AbilityCheck">Checks</LSTag>.': 'Завдайте додаткової [1] під час атаки цілі й надайте їй <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> статури.',
    'Deal an additional [1] when you attack the target and impart <LSTag Tooltip="Disadvantage">Disadvantage</LSTag> on Intelligence <LSTag Tooltip="AbilityCheck">Checks</LSTag>.': 'Завдайте додаткової [1] під час атаки цілі й надайте їй <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> інтелекту.',
    'Deal an additional [1] when you attack the target and impart <LSTag Tooltip="Disadvantage">Disadvantage</LSTag> on Wisdom <LSTag Tooltip="AbilityCheck">Checks</LSTag>.': 'Завдайте додаткової [1] під час атаки цілі й надайте їй <LSTag Tooltip="Disadvantage">заваду</LSTag> для <LSTag Tooltip="AbilityCheck">перевірок</LSTag> мудрості.',
}


MANUAL_PHRASES = {
    "One Закляття with Slot Закляття Хід": "Одне закляття з чарункою заклять за хід",
    "Cloak of Тінь": "Плащ тіней",
    "Scroll of Голодний Клинок": "Сувій Голодного клинка",
    "Scroll of Уламок розуму": "Сувій Уламка розуму",
    "Vex": "Збентеження",
    "One Spell with a Spell Slot per Turn": "Одне закляття з чарункою заклять за хід",
    "Body Warping of Gorgoroth": "Викривлення тіла Ґорґорота",
    "Scroll of Body Warping of Gorgoroth": "Сувій Викривлення тіла Ґорґорота",
    "Scroll of Ballistic": "Сувій балістики",
    "Elemental Attunement": "Стихійне налаштування",
    "Elemental Tunement": "Стихійне налаштування",
    "Tasha's Hideous Laughter": "Огидний сміх Таші",
    "Eladrin Seasons": "Пори року еладрінів",
    "Hunter’s Prey": "Здобич мисливця",
    "Hunter's Prey": "Здобич мисливця",
    "Hunter’s Lore": "Знання мисливця",
    "Hunter's Lore": "Знання мисливця",
    "Hunter's Mark": "Мітка мисливця",
    "Phantom Steed": "Примарний скакун",
    "Usable Classes": "Доступні класи",
    "Steel Defender": "Сталевий захисник",
    "Death Armor": "Обладунок смерті",
    "Cloak of Shadow": "Плащ тіней",
    "Unnerving Aura": "Бентежна аура",
    "Forge Domain": "Домен ковальства",
    "Aura of Vitality": "Аура життєвої сили",
    "Sorcerous Burst": "Чародійський вибух",
    "Blood Bolt": "Кривавий заряд",
    "Minor Elementals": "Малі стихійники",
    "Wizard's Savant": "Мудрець-чарівник",
    "Divine Spark": "Божественна іскра",
    "Spectral Slash": "Примарний розтин",
    "Void Strike Recast": "Повторний Удар порожнечі",
    "Sun Bolt": "Сонячний заряд",
    "Enervation Target": "Ціль Виснаження",
    "Rangers Companion": "Звір-супутник слідопита",
    "Acrobatics": "Акробатика",
    "Arcana": "Таїнства",
    "Athletics": "Атлетизм",
    "Deception": "Обман",
    "History": "Історія",
    "Insight": "Проникливість",
    "Intimidation": "Залякування",
    "Investigation": "Обстеження",
    "Medicine": "Медицина",
    "Nature": "Природа",
    "Perception": "Відчуття",
    "Performance": "Артистичність",
    "Persuasion": "Переконливість",
    "Religion": "Релігія",
    "Sleight of Hand": "Спритність рук",
    "Stealth": "Непомітність",
    "Survival": "Виживання",
    "Invisible": "Невидимість",
    "Unconscious": "Непритомність",
    "Poisoned": "Отруєння",
    "Paralyzed": "Параліч",
    "Stunned": "Приголомшення",
    "Disease": "Хвороба",
    "Sleep": "Сон",
    "Confusion": "Збентеження",
    "Counterspell": "Чароспин",
    "Stoneskin": "Кам’яна шкіра",
    "Entangle": "Заплутування",
    "Darkness": "Пітьма",
    "Expertise": "Експертність",
    "Shape-Shifter": "Перевертень",
    "Compleded Duel": "Вимушений двобій",
    "Hell’s Lash": "Батіг Пекла",
    "Enervation": "Виснаження",
    "Enwebbed": "Обплутаний",
    "Venomous": "Отруйний",
    "Spectral": "Примарний",
    "Raging": "У люті",
    "raging": "у люті",
    "Charge": "Натиск",
    "Void": "Порожнеча",
    "Throws": "Кидки протидії",
    "Rolls": "Кидки",
    "Recast": "Повторне застосування",
    "Companion": "Супутник",
    "Bite": "Укус",
    "Contagion": "Зараза",
    "Domain": "Домен",
    "Hide": "Сховатися",
    "Flare": "Спалах",
    "Target": "Ціль",
    "Swing": "Гойдання",
    "Step": "Крок",
    "Beak": "Дзьоб",
    "Claws": "Пазурі",
    "Tusk": "Ікло",
    "Savant": "Мудрець",
    "seal": "печать",
    # Rules/UI terminology.
    "Magic Initiate": "Магічний хист",
    "Origin Feat": "Риса походження",
    "War Caster": "Бойовий заклинач",
    "Wild Magic Surge": "Сплеск дикої магії",
    "Extra Attack": "Додаткова атака",
    "Cunning Strike": "Хитрий удар",
    "Heroic Inspiration": "Героїчне натхнення",
    "Attack Roll": "Кидок атаки",
    "Saving Throw": "Кидок протидії",
    "Reckless Attack": "Зухвала атака",
    "Forceful Blow": "Силовий удар",
    "Hamstring Blow": "Удар по сухожиллю",
    "Unarmed Strike": "Удар голіруч",
    "Attack action": "дія «Атака»",
    "Bonus Action": "Вторинна дія",
    "Channel Divinity": "Боже наснаження",
    "Bardic Inspiration": "Бардівське натхнення",
    "Warding Flare": "Охоронний спалах",
    "Pact Magic": "Магія пакту",
    "Radiant Damage": "Променева шкода",
    "Necrotic Damage": "Некротична шкода",
    "Force Damage": "Силова шкода",
    "Temporary Hit Points": "Тимчасові очки здоров’я",
    "Hit Points": "Очки здоров’я",
    "Hit Point": "Очко здоров’я",
    "Spell Slots": "Чарунки заклять",
    "Spell Slot": "Чарунка заклять",
    "Short Rest": "Короткий відпочинок",
    "Long Rest": "Довгий відпочинок",
    "Armour Class": "Рівень захисту",
    "Armor Class": "Рівень захисту",
    "Difficulty Class": "Межа складності",
    "Proficiency Bonus": "Бонус спеціалізації",
    "Opportunity Attack": "Принагідна атака",
    "Opportunity Attacks": "Принагідні атаки",
    "Ability Checks": "Перевірки характеристик",
    "Ability Check": "Перевірка характеристики",
    "Attack Rolls": "Кидки атаки",
    "Spell Save DC": "МС закляття",
    # Official BG3 spell/feature names commonly left intact by MT.
    "Charm Person": "Причарування особи",
    "Mirror Image": "Віддзеркалення",
    "Dancing Lights": "Танок вогників",
    "Chill Touch": "Крижаний дотик",
    "Booming Blade": "Громовий клинок",
    "Mind Sliver": "Уламок розуму",
    "Minor Illusion": "Мала ілюзія",
    "Shocking Grasp": "Шоковий хват",
    "Spare the Dying": "Пощада",
    "Sword Burst": "Вибух клинків",
    "Toll the Dead": "Подзвін",
    "True Strike": "Певний удар",
    "Vengeful Blade": "Мстивий клинок",
    "Word of Radiance": "Слово сяйва",
    "False Life": "Удаване життя",
    "Find Familiar": "Пошук джурозвіра",
    "Healing Word": "Цілюще слово",
    "Mage Armor": "Магічна броня",
    "Mage Armour": "Магічна броня",
    "Magic Missile": "Магічний залп",
    "Shield of Faith": "Щит віри",
    "Speak with Animals": "Розмова з тваринами",
    "Green-Flame Blade": "Клинок зеленого полум’я",
    "Tide of Darkness": "Хвиля пітьми",
    "Subtle Spell": "Непомітне закляття",
    "Empowered Spell": "Посилене закляття",
    "Enhanced Critical": "Посилене критичне влучання",
    "Unarmed Attack": "Атака голіруч",
    "Spell Disruption": "Зрив закляття",
    "Eldritch Smite": "Потойбічна кара",
    "Brutal Strike": "Жорстокий удар",
    "Dreadful Strike": "Жахливий удар",
    "Thirsting Blade": "Спраглий клинок",
    "Eldritch Mind": "Потойбічний розум",
    "Eldritch Hexed": "Потойбічне прокляття",
    "Eldritch Hex": "Потойбічне прокляття",
    "Psionic Energy Die": "Кістка псіонічної енергії",
    "Psionic Energy": "Псіонічна енергія",
    "Psionic Strike": "Псіонічний удар",
    "Bardic Die": "Бардівська кістка",
    "Bardic Damage": "Бардівська шкода",
    "Ki Point": "Очко Кі",
    "Fey Wanderer Spells": "Закляття фейського мандрівника",
    "Fey Wanderer": "Фейський мандрівник",
    "Psionic Spells": "Псіонічні закляття",
    "Circle Spells": "Закляття кола",
    "General Feats": "Загальні риси",
    "Origin Feats": "Риси походження",
    "Quick Draw": "Швидке вихоплення",
    "Steady Aim": "Виважене прицілювання",
    "Stalker’s Flurry": "Шквал переслідувача",
    "Uncanny Dodge": "Неймовірний ухил",
    "Psychic Blades": "Психічні клинки",
    "Steps of the Fey": "Кроки фей",
    "Hand of Healing": "Цілюща долоня",
    "Flurry of Healing": "Шквал зцілення",
    "Hand of Harm": "Згубна долоня",
    "Flurry of Harm": "Шквал шкоди",
    "Spirits from Beyond": "Духи з потойбіччя",
    "Forgotten Realms": "Забуті Королівства",
    "Heroes of Faerun": "Герої Фаеруну",
    "Tyro of the Gauntlet": "Учень Рукавиці",
    "Purple Dragon Rook": "Тура Пурпурового Дракона",
    "Zhentarim Ruffian": "Жентарімський головоріз",
    "Tropical Land": "Тропічні землі",
    "Dragon Shape": "Драконяча подоба",
    "Storm Prophetic": "Буреві пророцтва",
    "Arcane Armor": "Містична броня",
    "Arcane Jolt": "Містичний поштовх",
    "Arcane Vigor": "Містична бадьорість",
    "Arcane Empowerment": "Містичне посилення",
    "Eldritch Cannon": "Потойбічна гармата",
    "Lightning Launcher": "Блискавкомет",
    "Thunder Pulse": "Громовий імпульс",
    "Infernal Conduit": "Пекельний провідник",
    "Gestalt Anchor": "Гештальт-якір",
    "Strike of the Giants": "Удар велетнів",
    "Giant’s Might": "Міць велетня",
    "Stone’s Endurance": "Витривалість каменю",
    "Cloud’s Jaunt": "Стрибок хмари",
    "Hunter’s Mark": "Мітка мисливця",
    "Draining Slash": "Виснажливий розтин",
    "Harrowing Blade": "Болісний клинок",
    "Stymying Mark": "Сковувальна мітка",
    "Heavenly Wings": "Небесні крила",
    "Inner Radiance": "Внутрішнє сяйво",
    "Winter Walker Spells": "Закляття зимового мандрівника",
    "Winter Walkers": "Зимові мандрівники",
    "Genie's Splendor": "Пишнота джина",
    "Genie’s Splendor": "Пишнота джина",
    "Maverick Spirit": "Дух одинака",
    "Ride Them Down": "Зім’яти на скаку",
    "Baleful Interdict": "Згубна заборона",
    "Mind Shapener": "Творець розуму",
    "Battle Smiths": "Бойові ковалі",
    "Bloodliches": "Кроволічі",
    "Painkillers": "Болеглушники",
    "Painkiller": "Болеглушник",
    "Death Defier": "Зневажник смерті",
    "Dreadnaught": "Дредноут",
    "Risk Dice": "Кістки ризику",
    "Gut Shot": "Постріл у живіт",
    "Stand as One": "Стояти разом",
    "Cold Caster": "Заклинач холоду",
    "Enclave Magic": "Магія анклаву",
    "Mythal Touched": "Торкнутий міфалем",
    "Zhentarim Tactics": "Жентарімська тактика",
    "Poker Face": "Незворушне обличчя",
    "Highway Rider": "Дорожній вершник",
    "Shadowy Figments": "Тіньові примари",
    "Shadowmasters": "Володарі тіней",
    "Frightful Start": "Моторошний початок",
    "Wardaway": "Відвернення",
    "Tree Stride": "Крок крізь дерева",
    "Two-Handed": "Дворучна",
    "Hop Up": "Підскок",
    "Pole Strike": "Удар древком",
    "Reactive Strike": "Відплатний удар",
    "Find Steed": "Пошук скакуна",
    "Remove Curse": "Зняття прокляття",
    "Hold Person": "Утримання особи",
    "Steel Wind Strike": "Удар сталевого вітру",
    "Danse Macabre": "Танок смерті",
    "Color Spray": "Барвисті бризки",
    "Expeditious Retreat": "Стрімкий відступ",
    "Expeditive Retreat": "Стрімкий відступ",
    "Sleight of Hand": "Спритність рук",
    "Purple Dragon": "Пурпуровий Дракон",
    "Baldur’s Gate": "Брама Балдура",
    "Fey Touched": "Торкнутий феями",
    "Shadow Touched": "Торкнутий тінню",
    "Dragon Hide": "Драконяча шкура",
    "Spellfire Spark": "Іскра чаровогню",
    "Doom Song": "Пісня приречення",
    "Hollow Warden": "Порожній вартовий",
    "Wrath of the Wild": "Гнів дикої природи",
    "Hellspeakers": "Промовці Пекла",
    "Red Cant": "Червоний арґо",
    "Hell’s Cant": "Пекельний арґо",
    "Finger Guns": "Пальці-пістолети",
    "ColdFire": "Холодовогонь",
    "Coldfire": "Холодовогонь",
    "Spellshot": "Заклятопостріл",
    "Spellfire": "Чаровогонь",
    "Shadowfell": "Царство Тіней",
    "Feywild": "Фейський простір",
    "Darkvision": "Темнобачення",
    "Blindsight": "Сліпобачення",
    "Quarterstaff": "Бойовий посох",
    "Longstrider": "Довгоніг",
    "Cloudkill": "Згубна хмара",
    "Revivify": "Повернення до життя",
    "Shillelagh": "Ґирлиґа",
    "Moonbeam": "Місячний промінь",
    "Daylight": "Денне світло",
    "Steel Wind": "Сталевий вітер",
    "Fireball": "Вогняна куля",
    "Shatter": "Розтрощення",
    "Guidance": "Направляння",
    "Hunter's Rime": "Паморозь мисливця",
    "Marid’s Surge": "Сплеск марида",
    "Dread Allegiance": "Грізна відданість",
    "Starry Wisp": "Зоряний вогник",
    "Prestidigitation": "Дрібні чари",
    "Agile Strikes": "Спритні удари",
    "Fade Away": "Зникнення",
    "Shadowmaster": "Володар тіней",
    "Bladessons": "Пісня клинка",
    "Bind Pact": "Скріпити пакт",
    "Umbral Killer": "Тіньовий убивця",
    "Fire’s Burn": "Опік вогню",
    "Frost’s Chill": "Холод морозу",
    "Hill’s Tumble": "Перекид пагорба",
    "Divine Points": "Божественні очки",
    "Rend the Blasphemous": "Роздерти богохульника",
    "Vitriolic Sphere": "Їдка сфера",
    "Synaptic Static": "Синаптичний розряд",
    # Classes, abilities, and conditions use the shipped Ukrainian localization.
    "Arcane Trickster": "Містичний штукар",
    "Monster Hunter": "Мисливець на чудовиськ",
    "Battle Smith": "Бойовий коваль",
    "Weapon Mastery": "Майстерність зброї",
    "Greatclub": "Велика довбня",
    "Heavy Crossbow": "Важкий арбалет",
    "Warhammer": "Бойовий молот",
    "Constitution": "Статура",
    "Dexterity": "Спритність",
    "Intelligence": "Інтелект",
    "Charisma": "Харизма",
    "Strength": "Сила",
    "Wisdom": "Мудрість",
    "Prone": "Повалення",
    "Enraged": "У люті",
    "Cantrips": "Замовляння",
    "Cantrip": "Замовляння",
    "Advantage": "Перевага",
    "Disadvantage": "Завада",
    "Resistance": "Стійкість",
    "Radiant": "Променева",
    "Necrotic": "Некротична",
    "Force": "Силова",
    "Fighter": "Боєць",
    "Wizard": "Чарівник",
    "Cleric": "Клірик",
    "Rogue": "Пройдисвіт",
    "Barbarian": "Варвар",
    "Sorcerer": "Чародій",
    "Warlock": "Чаклун",
    "Paladin": "Паладин",
    "Ranger": "Слідопит",
    "Druid": "Друїд",
    "Monk": "Монах",
    "Bard": "Бард",
    "Pike": "Піка",
    "Rage": "Лють",
    "Tough": "Гартований",
    "Sentinel": "Вартовий",
    "Feat": "Риса",
    "Trip": "Підсічка",
    "Terrify": "Залякування",
    "Push": "Поштовх",
    "Turn": "Хід",
    "Heal": "Зцілення",
    "Checks": "Перевірки",
    "Check": "Перевірка",
    "Proficient": "Спеціалізований",
    "Proficiency": "Спеціалізація",
    "Concentration": "Зосередження",
    "modifier": "модифікатор",
    "Modifier": "Модифікатор",
    "reaction": "реагування",
    "familiar": "джурозвір",
    "mastery": "майстерності",
    "Light": "Легка",
    "Attack": "Атака",
    "Dash": "Ривок",
    "Blur": "Розмиття",
    "Blink": "Миготіння",
    "Hexblade": "Відьомський клинок",
    "Hex": "Прокляття",
    "Bludgeoning": "Забійна",
    "Finesse": "Фехтувальна",
    "Thrown": "Метальна",
    "Web": "Павутиння",
    "Haste": "Прискорення",
    "Blindness": "Сліпота",
    "Blight": "Мор",
    "Bless": "Благословення",
    "Shield": "Щит",
    "Fear": "Страх",
    "Invisibility": "Невидимість",
    "Disengage": "Відхід",
    "Stealth": "Скритність",
    "Perception": "Уважність",
    "Spear": "Спис",
    "Heavy": "Важка",
    "Reach": "Довга",
    "Versatile": "Універсальна",
    "Topple": "Підсічка",
    "Sap": "Знесилення",
    "Slow": "Сповільнення",
    "Tropical": "Тропічний",
    "Harper": "Арфіст",
    "Artificer": "Винахідник",
    "Illrigger": "Ілріґер",
    "illrigger": "ілріґер",
    "Dragonscarred": "Драконошрамний",
    "Kensei": "Кенсей",
    "Soulknife": "Клинок душі",
    "Lifedrinker": "Життєпивця",
    "Skulker": "Скрадач",
    "Bladesinger": "Співець клинка",
    "Dispater": "Диспатер",
    "Bhaal": "Баал",
    "Bane": "Бейн",
    "Archfey": "Архіфея",
    "Gnome": "Гном",
    "Harper": "Арфіст",
    "Renegade": "Відступник",
    "Wayfarer": "Мандрівник",
    "Ruffian": "Головоріз",
    "Merc": "Найманець",
    "Tyro": "Учень",
    "Guardian": "Захисник",
    "Infiltrator": "Розвідник",
    "Dread": "Жах",
    "Slasher": "Рубака",
    "Devastator": "Спустошувач",
    "Sharpshooter": "Снайпер",
    "Hew": "Розсікання",
    "Snare": "Пастка",
    "Throw": "Кидок",
    "Features": "Особливості",
    "Dice": "Кістки",
    "Die": "Кістка",
    "Magic": "Магія",
    "Spell": "Закляття",
    "Spells": "Закляття",
    "Feats": "Риси",
    "Origin": "Походження",
    "Arcane": "Містичний",
    "Eldritch": "Потойбічний",
    "Smite": "Кара",
    "Strike": "Удар",
    "Blade": "Клинок",
    "Hand": "Долоня",
    "Harm": "Шкода",
    "Healing": "Зцілення",
    "Dragon": "Дракон",
    "Storm": "Буря",
    "Thunder": "Грім",
    "Lightning": "Блискавка",
    "Cold": "Холод",
    "Fire": "Вогонь",
    "Frost": "Мороз",
    "Cloud": "Хмара",
    "Stone": "Камінь",
    "Hill": "Пагорб",
    "Winter": "Зима",
    "Shadow": "Тінь",
    "Blind": "Засліплення",
    "Blinded": "Засліплений",
    "Charmed": "Причарований",
    "Silenced": "Заглушений",
    "Immunity": "Імунітет",
    "Overkill": "Надмірна шкода",
    "Charges": "Заряди",
    "Skilled": "Умілець",
    "Lucky": "Щасливчик",
    "Alert": "Пильний",
    "Lissome": "Гнучкий",
    "Maverick": "Одинак",
    "General": "Загальні",
    "Upgrade": "Поліпшення",
    "Anchor": "Якір",
    "Pulse": "Імпульс",
    "Jolt": "Поштовх",
    "Conduit": "Провідник",
    "Infused": "Наповнений",
    "Garrotting": "Удушення",
    "Summoner": "Закликач",
    "Protector": "Захисник",
    "Cone": "Конус",
    "Slash": "Розтин",
    "Goad": "Провокація",
    "Meow": "Няв",
    "Legerdemain": "Спритність рук",
    "legerdemain": "спритність рук",
    "Fey": "Феї",
    "AH-sih-mar": "А-сі-мар",
    "Allegiance": "Відданість",
    "Demolisher": "Руйнівник",
    "Genie": "Джин",
    "Mythal": "Міфаль",
    "Shroud": "Саван",
    "Walker": "Мандрівник",
    "efreet": "іфрит",
    "Rune": "Руна",
    "Enweb": "Обплутування",
    "Ensanring": "Обплутувальний",
    "Ensnaring": "Обплутувальний",
    "Shining": "Сяйна",
    "Giant": "Велетень",
    "Grasp": "Захват",
    "CR": "РН",
    "Hungering": "Голодний",
    "Dominated": "Підпорядкований",
    "and": "і",
    "AC": "РЗ",
    "DC": "МС",
}


POSTPROCESS = (
    (r"\bВогонь[’']s Burn\b", "Опік вогню"),
    (r"\bМороз[’']s Chill\b", "Холод морозу"),
    (r"\bПагорб[’']s Tumble\b", "Перекид пагорба"),
    (r"\b(?:очки|бали) життя\b", "очки здоров’я"),
    (r"(?-i:\bМагічний ініціатор\b)", "Магічний хист"),
    (r"(?-i:\bмагічний ініціатор\b)", "магічний хист"),
    (r"\bАдепт Елдріча\b", "Потойбічний адепт"),
    (r"\bІнтернет\b", "Павутиння"),
    (r"\bпулом\b", "запасом"),
    (r"\bпулі\b", "запасі"),
    (r"\bпулу\b", "запасу"),
    (r"\bпула\b", "запасу"),
    (r"\bпул\b", "запас"),
    (r"\bбасейнами\b", "запасами"),
    (r"\bбасейнів\b", "запасів"),
    (r"\bбасейну\b", "запасу"),
    (r"\bбасейн\b", "запас"),
    (r"\bЧеками\b", "Перевірками"),
    (r"\bЧеків\b", "Перевірок"),
    (r"\bЧеки\b", "Перевірки"),
    (r"\bЧеком\b", "Перевіркою"),
    (r"\bЧеку\b", "Перевірці"),
    (r"\bЧек\b", "Перевірка"),
    (r"\bчеками\b", "перевірками"),
    (r"\bчеків\b", "перевірок"),
    (r"\bчеки\b", "перевірки"),
    (r"\bчеком\b", "перевіркою"),
    (r"\bчеку\b", "перевірці"),
    (r"\bчек\b", "перевірка"),
    (r"\bкубиками\b", "кістками"),
    (r"\bкубиків\b", "кісток"),
    (r"\bкубики\b", "кістки"),
    (r"\bкубиком\b", "кісткою"),
    (r"\bкубика\b", "кістки"),
    (r"\bкубику\b", "кістці"),
    (r"\bкубик\b", "кістка"),
    (r"\b(d\d+)s\b", r"\1"),
    (r"\bБардичного натхнення\b", "Бардівського натхнення"),
    (r"\bБардичному натхненню\b", "Бардівському натхненню"),
    (r"\bБардичним натхненням\b", "Бардівським натхненням"),
    (r"\bБардичне натхнення\b", "Бардівське натхнення"),
    (r"\bНанесення ран\b", "Завдання ран"),
    (r"\bнанесення ран\b", "завдання ран"),
    (r"\bнанести рани\b", "Завдання ран"),
    (r"\bнанесеній ([а-яіїєґ]+ шкоді)\b", r"завданій \1"),
    (r"\bнаноситься зброєю\b", "завдає зброя"),
    (r"\bдля нанесення ударів голіруч\b", "для ударів голіруч"),
    (r"\bколи ви наносите удар голіруч\b", "коли ви виконуєте удар голіруч"),
    (r"\bнанести один удар голіруч\b", "виконати один удар голіруч"),
    (r"\bНанесіть додатковий\b", "Завдайте додаткової"),
    (r"\bнанести додатковий\b", "завдати додаткової"),
    (r"\bшкоди від Сили\b", "силової шкоди"),
    (r"\bшкоди від сили\b", "силової шкоди"),
    (r"\bшкоду від Сили\b", "силову шкоду"),
    (r"\bшкоду від сили\b", "силову шкоду"),
    (r"\bшкода від Сили\b", "силова шкода"),
    (r"\bшкода від сили\b", "силова шкода"),
    (r"\bотримуючи шкоди\b", "зазнаючи шкоди"),
    (r"\bотримавши шкоди\b", "зазнавши шкоди"),
    (r"\bотримуєте (?=[^.!?]{0,80}\bшкод)\b", "зазнаєте "),
    (r"\bотримує (?=[^.!?]{0,80}\bшкод)\b", "зазнає "),
    (r"\bотримують (?=[^.!?]{0,80}\bшкод)\b", "зазнають "),
    (r"\bотримав (?=[^.!?]{0,80}\bшкод)\b", "зазнав "),
    (r"\bотримала (?=[^.!?]{0,80}\bшкод)\b", "зазнала "),
    (r"\bтворити закляття\b", "проказувати закляття"),
    (r"\bзаклинаєте\b", "проказуєте закляття"),
    (r"\bсвою реагування\b", "своє реагування"),
    (r"\bцю реагування\b", "це реагування"),
    (r"\bусі витрати\b", "усі витрачені використання"),
    (r"\bвсі витрати\b", "всі витрачені використання"),
    (r"\bусі використані засоби\b", "усі витрачені використання"),
    (r"\bвсі використані засоби\b", "всі витрачені використання"),
    (r"\bодне використане використання\b", "одне витрачене використання"),
    (r"\bстільки разів, скільки відповідає\b", "стільки разів, скільки дорівнює"),
    (r"\bпри невдалому рятуванні\b", "за невдалої протидії"),
    (r"\bпри успішному\b", "за успішної протидії"),
    (r"\bкидок протидії Статур\b", "кидок протидії статурою"),
    (r"\bПовалення»\b", "Повалення"),
    (r"\bПереляку»\b", "Переляку"),
    (r"\bкритичними ударами\b", "критичними влучаннями"),
    (r"\bкритичних ударів\b", "критичних влучань"),
    (r"\bкритичні удари\b", "критичні влучання"),
    (r"\bкритичним ударом\b", "критичним влучанням"),
    (r"\bкритичного удару\b", "критичного влучання"),
    (r"\bкритичний удар\b", "критичне влучання"),
    (r"\bатака потрапляє\b", "атака влучає"),
    (r"\bатака потрапила\b", "атака влучила"),
    (r"\bснаряд потрапляє в ціль\b", "снаряд влучає в ціль"),
    (r"\bпершій цілі, яку потрапите\b", "першій цілі, у яку влучите"),
    (r"\bвін потрапить або промахнеться\b", "він влучить чи промахнеться"),
    (r"\b(?:очок|балів) життя\b", "очок здоров’я"),
    (r"\b(?:очками|балами) життя\b", "очками здоров’я"),
    (r"\b(?:очко|бал) життя\b", "очко здоров’я"),
    # Core BG3 terminology. These rules intentionally run only over visible text,
    # leaving Larian tags and their attributes byte-for-byte intact.
    (r"\bМС (?:збереження|порятунку)(?: від)? заклять\b", "МС протидії закляттям"),
    (r"\bМС збереження закляття\b", "МС протидії закляттям"),
    (r"\bкидками (?:економії|збереження|порятунку)\b", "кидками протидії"),
    (r"\bкидків (?:економії|збереження|порятунку)\b", "кидків протидії"),
    (r"\bкидки (?:економії|збереження|порятунку)\b", "кидки протидії"),
    (r"\bкидком (?:економії|збереження|порятунку)\b", "кидком протидії"),
    (r"\bкидок (?:економії|збереження|порятунку)\b", "кидок протидії"),
    (r"\b(?:захисний|економний|рятівний|рятувальний) кидок\b", "кидок протидії"),
    (r"\b(?:захисні|економні|рятівні|рятувальні) кидки\b", "кидки протидії"),
    (r"\b(?:захисних|економних|рятівних|рятувальних) кидків\b", "кидків протидії"),
    (r"\b(?:захисним|економним|рятівним|рятувальним) кидком\b", "кидком протидії"),
    (r"\b(?:захисному|економному|рятівному|рятувальному) кидку\b", "кидку протидії"),
    (r"\b(?:захисних|економних|рятівних|рятувальних) кидках\b", "кидках протидії"),
    (r"\b(?:за|після|під час|при) невдал(?:ого|ому) (?:збереження|порятунку)\b", "за невдалої протидії"),
    (r"\bу випадку невдалого (?:збереження|порятунку)\b", "у разі невдалої протидії"),
    (r"\bу разі невдалого (?:збереження|порятунку)\b", "у разі невдалої протидії"),
    (r"\b(?:за|після|під час|при) (?:вдалому|вдалого|успішному|успішного) (?:збереженні|збереження|порятунку)\b", "за успішної протидії"),
    (r"\bу разі (?:вдалого|успішного) (?:збереження|порятунку)\b", "у разі успішної протидії"),
    (r"\bповторює збереження\b", "повторює кидок протидії"),
    (r"\bповторити збереження\b", "повторити кидок протидії"),
    (r"\bробить це збереження\b", "виконує цей кидок протидії"),
    (r"\bробити це збереження\b", "виконувати цей кидок протидії"),
    (r"\bробити збереження\b", "виконувати кидок протидії"),
    (r"\bдруге збереження\b", "другий кидок протидії"),
    (r"\bнаступного збереження\b", "наступного кидка протидії"),
    (r"\bрезультату збереження\b", "результату кидка протидії"),
    (r"\bзбереження в кінці\b", "кидок протидії наприкінці"),
    (r"\bзбереження коли\b", "кидок протидії, коли"),
    (r"\bпринагідну атаку\b", "принагідну атаку"),
    (r"\bатаку можливостей\b", "принагідну атаку"),
    (r"\bатакою можливостей\b", "принагідною атакою"),
    (r"\bатакою можливості\b", "принагідною атакою"),
    (r"\bатаки можливостей\b", "принагідні атаки"),
    (r"\bатак можливостей\b", "принагідних атак"),
    (r"\bатаками можливостей\b", "принагідними атаками"),
    (r"\bатака можливості\b", "принагідна атака"),
    (r"\bвикористовуючи чарунка заклять\b", "використовуючи чарунку заклять"),
    (r"\bвикористаний чарунка заклять\b", "використану чарунку заклять"),
    (r"\bвикористайте дію та чарунка заклять\b", "використайте дію та чарунку заклять"),
    (r"\bвикористовуйте дію та чарунка заклять\b", "використайте дію та чарунку заклять"),
    (r"\bнижчий за слот\b", "нижчий за чарунку"),
    (r"\bрівня слота\b", "рівня чарунки"),
    (r"\bіз цим слотом\b", "із цією чарункою"),
    (r"\bз цим слотом\b", "з цією чарункою"),
    (r"\bслотами\b", "чарунками"),
    (r"\bслотів\b", "чарунок"),
    (r"\bслоти\b", "чарунки"),
    (r"\bслотом\b", "чарункою"),
    (r"\bслота\b", "чарунки"),
    (r"\bслоту\b", "чарунці"),
    (r"\bслоті\b", "чарунці"),
    (r"\bслот\b", "чарунка"),
    (r"\bрадіаційними\b", "променевими"),
    (r"\bрадіаційних\b", "променевих"),
    (r"\bрадіаційною\b", "променевою"),
    (r"\bрадіаційної\b", "променевої"),
    (r"\bрадіаційному\b", "променевому"),
    (r"\bрадіаційній\b", "променевій"),
    (r"\bрадіаційне\b", "променеве"),
    (r"\bрадіаційну\b", "променеву"),
    (r"\bрадіаційна\b", "променева"),
    (r"\bшкоди від радіанта\b", "променевої шкоди"),
    (r"\bшкоду від радіанта\b", "променеву шкоду"),
    (r"\bшкода від радіанта\b", "променева шкода"),
    (r"\bпошкодження від радіанта\b", "променевої шкоди"),
    (r"\bпошкодження від радіації\b", "променевої шкоди"),
    (r"\bпошкодження радіантом\b", "променевої шкоди"),
    (r"\bрадіант(?:ом|а)?\b", "променева шкода"),
    (r"\bкидками (?:по|у)шкодження\b", "кидками шкоди"),
    (r"\bкидків (?:по|у)шкодження\b", "кидків шкоди"),
    (r"\bкидки (?:по|у)шкодження\b", "кидки шкоди"),
    (r"\bкидком (?:по|у)шкодження\b", "кидком шкоди"),
    (r"\bкидок (?:по|у)шкодження\b", "кидок шкоди"),
    (r"\bкубиками (?:по|у)шкоджень\b", "кістками шкоди"),
    (r"\bкубиків (?:по|у)шкоджень\b", "кісток шкоди"),
    (r"\bкубики (?:по|у)шкоджень\b", "кістки шкоди"),
    (r"\bкубика (?:по|у)шкодження\b", "кістки шкоди"),
    (r"\bкубик (?:по|у)шкодження\b", "кістка шкоди"),
    (r"\bматриц(?:я|ю|і) (?:по|у)шкоджень\b", "кістка шкоди"),
    (r"\bстійкість до (?:по|у)шкоджень\b", "стійкість до шкоди"),
    (r"\bстійкості до (?:по|у)шкоджень\b", "стійкості до шкоди"),
    (r"\bопір (?:по|у)шкодженню\b", "опір шкоді"),
    (r"\bотримує (?=[^.!?]{0,100}\b(?:по|у)шкодження\b)", "зазнає "),
    (r"\bотримують (?=[^.!?]{0,100}\b(?:по|у)шкодження\b)", "зазнають "),
    (r"\bотримуєте (?=[^.!?]{0,100}\b(?:по|у)шкодження\b)", "зазнаєте "),
    (r"(?-i:\bПошкодження\b)(?= (?:має|стає|збільшується|та зцілення|від|такого|цього|є))", "Шкода"),
    (r"\b(?:по|у)шкодженням\b", "шкодою"),
    (r"\b(?:по|у)шкодженню\b", "шкоді"),
    (r"\b(?:по|у)шкоджень\b", "шкоди"),
    (r"\bцього ушкодження\b", "цієї шкоди"),
    (r"(?-i:\bПошкодження\b)", "Шкода"),
    (r"(?-i:\bпошкодження\b)", "шкоди"),
    (r"\bзазнає додаткову шкоду\b", "зазнає додаткової шкоди"),
    (r"\bотримує шкоди Силою\b", "зазнає силової шкоди"),
    (r"\bотримує додаткову шкоду 1d8 від променева шкода\b", "зазнає додаткової променевої шкоди 1d8"),
    (r"\bвід променева шкода\b", "від променевої шкоди"),
    (r"\bКонституцією\b", "Статурою"),
    (r"\bКонституцій\b", "Статур"),
    (r"\bКонституції\b", "Статури"),
    (r"\bКонституцію\b", "Статуру"),
    (r"\bКонституція\b", "Статура"),
    (r"\bстан [«\"]?Зачарований[»\"]?\b", "стан Причарування"),
    (r"\bстан [«\"]?Наляканий[»\"]?\b", "стан Переляку"),
    (r"\bпідтримувати зосередження\b", "підтримувати концентрацію"),
    (r"\bпідтримки зосередження\b", "підтримання концентрації"),
    (r"\bЗосередження на заклятті\b", "Концентрації на заклятті"),
    (r"\bочками Концентрація\b", "очками зосередження"),
    (r"\bочок Концентрація\b", "очок зосередження"),
    (r"\bочки Концентрація\b", "очки зосередження"),
    (r"\bочко Концентрація\b", "очко зосередження"),
    (r"\bЕліксир незрівнянного Концентрація\b", "Еліксир незрівнянного зосередження"),
    (r"(?-i:\bЗосередження\b)", "Концентрація"),
    (r"\bв чеку Харизма \(Артистичність\)\b", "у перевірці Харизми (Артистичність)"),
    (r"\bЕкспертність у Переконливість і Обман Чеки\b", "Експертність у перевірках Переконання й Обману"),
    (r"\bНевигідність\b", "Завада"),
    (r"\bНевигідний кидок кидків протидії\b", "заваду для кидків протидії"),
    (r"\bНевигідний кидок протидії\b", "заваду для кидка протидії"),
    (r"\bНевигідний кидок\b", "заваду для кидка"),
    (r"\bкидок невигідним\b", "кидок із завадою"),
    (r"\bстан [«\"]?Схильність[»\"]?\b", "стан Повалення"),
    (r"\b[«\"]Побудова[»\"]\b", "Статура"),
    (r"\bПобудова\b", "Статура"),
    (r"\bНеозброєним ударом\b", "ударом голіруч"),
    (r"\bнеозброєним ударом\b", "ударом голіруч"),
    (r"\bБеззбройним ударом\b", "ударом голіруч"),
    (r"\bбеззбройним ударом\b", "ударом голіруч"),
    (r"\bБеззбройного удару\b", "удару голіруч"),
    (r"\bбеззбройного удару\b", "удару голіруч"),
    (r"\bбеззбройних ударів\b", "ударів голіруч"),
    (r"\bбеззбройних удари\b", "удари голіруч"),
    (r"\bбеззбройними ударами\b", "ударами голіруч"),
    (r"\bбеззбройні удари\b", "удари голіруч"),
    (r"\bбеззбройний удар\b", "удар голіруч"),
    (r"\bнеозброєний удар\b", "удар голіруч"),
    (r"\bударом без зброї\b", "ударом голіруч"),
    (r"\bудару без зброї\b", "удару голіруч"),
    (r"\bударів без зброї\b", "ударів голіруч"),
    (r"\bударами без зброї\b", "ударами голіруч"),
    (r"\bудари без зброї\b", "удари голіруч"),
    (r"\bудар без зброї\b", "удар голіруч"),
    (r"\bсвою Божественність каналу\b", "своє Боже наснаження"),
    (r"\bсвоєї Божественності каналу\b", "свого Божого наснаження"),
    (r"\bвашої Божественності каналу\b", "вашого Божого наснаження"),
    (r"\bсвою божественність каналу\b", "своє Боже наснаження"),
    (r"\bсвоєї божественності каналу\b", "свого Божого наснаження"),
    (r"\bвашої божественності каналу\b", "вашого Божого наснаження"),
    (r"\bсвою Клятву каналу\b", "своє Боже наснаження"),
    (r"\bвашу Клятву каналу\b", "ваше Боже наснаження"),
    (r"\bвашої Клятви каналу\b", "вашого Божого наснаження"),
    (r"\bБожественність каналу\b", "Боже наснаження"),
    (r"\bБожественності каналу\b", "Божого наснаження"),
    (r"\bбожественність каналу\b", "Боже наснаження"),
    (r"\bбожественності каналу\b", "Божого наснаження"),
    (r"\bКлятву каналу\b", "Боже наснаження"),
    (r"\bКлятви каналу\b", "Божого наснаження"),
    (r"\bКлятва каналу\b", "Боже наснаження"),
    (r"\bвардом\b", "оберегом"),
    (r"\bвардів\b", "оберегів"),
    (r"\bварди\b", "обереги"),
    (r"\bварда\b", "оберега"),
    (r"\bварду\b", "оберегу"),
    (r"\bвард\b", "оберіг"),
    (r"\bочками чарівництва\b", "очками чародійства"),
    (r"\bочків чарівництва\b", "очок чародійства"),
    (r"\bочки чарівництва\b", "очки чародійства"),
    (r"\bочко чарівництва\b", "очко чародійства"),
    (r"\bочками магії\b", "очками чародійства"),
    (r"\bочків магії\b", "очок чародійства"),
    (r"\bочки магії\b", "очки чародійства"),
    (r"\bочок магії\b", "очок чародійства"),
    (r"\bочко магії\b", "очко чародійства"),
    (r"\bклириками\b", "кліриками"),
    (r"\bклириків\b", "кліриків"),
    (r"\bклирика\b", "клірика"),
    (r"\bклирик\b", "клірик"),
    (r"\bклериками\b", "кліриками"),
    (r"\bклериків\b", "кліриків"),
    (r"\bклерики\b", "клірики"),
    (r"\bклерика\b", "клірика"),
    (r"\bклерик\b", "клірик"),
    (r"\bТіфлінгами\b", "Бісинами"),
    (r"\bТіфлінгів\b", "Бісинів"),
    (r"\bТіфлінги\b", "Бісини"),
    (r"\bТіфлінгом\b", "Бісином"),
    (r"\bТіфлінга\b", "Бісина"),
    (r"\bТіфлінг\b", "Бісин"),
    (r"\bтіфлінгами\b", "бісинами"),
    (r"\bтіфлінгів\b", "бісинів"),
    (r"\bтіфлінги\b", "бісини"),
    (r"\bтіфлінгом\b", "бісином"),
    (r"\bтіфлінга\b", "бісина"),
    (r"\bтіфлінг\b", "бісин"),
    (r"\bрейнджерами\b", "слідопитами"),
    (r"\bрейнджерів\b", "слідопитів"),
    (r"\bрейнджерах\b", "слідопитах"),
    (r"\bрейнджером\b", "слідопитом"),
    (r"\bрейнджеру\b", "слідопитові"),
    (r"\bрейнджера\b", "слідопита"),
    (r"\bрейнджери\b", "слідопити"),
    (r"\bрейнджер\b", "слідопит"),
    (r"\bіллригерами\b", "ілріґерами"),
    (r"\bіллригерів\b", "ілріґерів"),
    (r"\bіллригери\b", "ілріґери"),
    (r"\bіллригером\b", "ілріґером"),
    (r"\bіллригера\b", "ілріґера"),
    (r"\bіллригер\b", "ілріґер"),
    (r"\bнавиками\b", "навичками"),
    (r"\bнавиків\b", "навичок"),
    (r"\bнавики\b", "навички"),
    (r"\bнавиком\b", "навичкою"),
    (r"\bнавику\b", "навички"),
    (r"\bнавик\b", "навичка"),
    (r"\bвпадете Вне свідомості\b", "впадете в стан Непритомності"),
    (r"\bВне свідомості\b", "стан Непритомності"),
    (r"\bпопаданнях\b", "влучаннях"),
    (r"\bпопаданні\b", "влучанні"),
    (r"\bпопадання\b", "влучання"),
    (r"\bКонь\b", "Кінь"),
    (r"\bконь\b", "кінь"),
    (r"\bтестах D20\b", "перевірках D20"),
    (r"\bтесті D20\b", "перевірці D20"),
    (r"\bтесту D20\b", "перевірки D20"),
    (r"\bтест D20\b", "перевірку D20"),
    (r"\bтести D20\b", "перевірки D20"),
    (r"\bтестами\b", "перевірками"),
    (r"\bтестах\b", "перевірках"),
    (r"\bтестів\b", "перевірок"),
    (r"\bтести\b", "перевірки"),
    (r"\bтестом\b", "перевіркою"),
    (r"\bтесті\b", "перевірці"),
    (r"\bтесту\b", "перевірки"),
    (r"\bтест\b", "перевірку"),
    (r"\bневдалого сейва\b", "невдалої протидії"),
    (r"\bневдалих сейвів\b", "невдалих кидків протидії"),
    (r"\bпід час сейвів\b", "під час кидків протидії"),
    (r"\bсейвами\b", "кидками протидії"),
    (r"\bсейвів\b", "кидків протидії"),
    (r"\bсейви\b", "кидки протидії"),
    (r"\bсейвом\b", "кидком протидії"),
    (r"\bсейва\b", "кидка протидії"),
    (r"\bсейв\b", "кидок протидії"),
    (r"\bстрайками\b", "ударами"),
    (r"\bстрайків\b", "ударів"),
    (r"\bстрайки\b", "удари"),
    (r"\bстрайком\b", "ударом"),
    (r"\bстрайку\b", "удару"),
    (r"\bстрайка\b", "удару"),
    (r"\bстрайк\b", "удар"),
    (r"\bне витрачаючи чарунка заклять\b", "не витрачаючи чарунку заклять"),
    (r"\bвитративши чарунка заклять\b", "витративши чарунку заклять"),
    (r"\bвикориставши чарунка заклять\b", "використавши чарунку заклять"),
    (r"\bвикористовує чарунка заклять\b", "використовує чарунку заклять"),
    (r"\bвикористаєте чарунка заклять\b", "використаєте чарунку заклять"),
    (r"\bВитратьте чарунка заклять\b", "Витратьте чарунку заклять"),
    (r"\bвитрачати чарунка заклять\b", "витрачати чарунку заклять"),
    (r"\bвитратити чарунка заклять\b", "витратити чарунку заклять"),
    (r"\bодин додатковий чарунка заклять\b", "одну додаткову чарунку заклять"),
    (r"\bодин чарунка заклять\b", "одну чарунку заклять"),
    (r"\bцей чарунка заклять\b", "цю чарунку заклять"),
    (r"\bіншого чарунки заклять\b", "іншої чарунки заклять"),
    (r"\bвитраченого чарунки заклять\b", "витраченої чарунки заклять"),
    (r"\bОтримано чарунка заклять\b", "Отримано чарунку заклять"),
    (r"\bрозблокувати чарунка заклять\b", "розблокувати чарунку заклять"),
    (r"\bрівень ([1-9]) чарунка заклять\b", r"рівень \1 чарунки заклять"),
    (r"\bдоки не буде використано цю чарунку заклять\b", "доки не буде використана ця чарунка заклять"),
    (r"\bпоки не буде використано цю чарунку заклять\b", "поки не буде використана ця чарунка заклять"),
    (r"\bкидок протидії Сили\b", "кидок протидії силою"),
    (r"\bкидок протидії Спритності\b", "кидок протидії спритністю"),
    (r"\bкидок протидії Статури\b", "кидок протидії статурою"),
    (r"\bкидок протидії Інтелекту\b", "кидок протидії інтелектом"),
    (r"\bкидок протидії Мудрості\b", "кидок протидії мудрістю"),
    (r"\bкидок протидії Харизми\b", "кидок протидії харизмою"),
    (r"\bкидки протидії Сили\b", "кидки протидії силою"),
    (r"\bкидки протидії Спритності\b", "кидки протидії спритністю"),
    (r"\bкидки протидії Статури\b", "кидки протидії статурою"),
    (r"\bкидки протидії Інтелекту\b", "кидки протидії інтелектом"),
    (r"\bкидки протидії Мудрості\b", "кидки протидії мудрістю"),
    (r"\bкидки протидії Харизми\b", "кидки протидії харизмою"),
    (r"\bкидках протидії Інтелекту, Мудрості та Харизми\b", "кидках протидії інтелектом, мудрістю та харизмою"),
    (r"^у разі\b", "У разі"),
    (r"(?<=[.!?] )у разі\b", "У разі"),
    (r"(?<=\n)у разі\b", "У разі"),
    (r"^за (?:невдалої|успішної) протидії\b", lambda match: match.group(0).capitalize()),
    (r"(?<=[.!?] )за (?:невдалої|успішної) протидії\b", lambda match: match.group(0).capitalize()),
    (r"(?<=\n)за (?:невдалої|успішної) протидії\b", lambda match: match.group(0).capitalize()),
    (r"\bперевірках d20\b", "перевірках D20"),
    (r"\bперевірки d20\b", "перевірки D20"),
    (r"\bкидків протидії Сили\b", "кидків протидії силою"),
    (r"\bкидків протидії Спритності\b", "кидків протидії спритністю"),
    (r"\bкидків протидії Статури\b", "кидків протидії статурою"),
    (r"\bкидків протидії Інтелекту\b", "кидків протидії інтелектом"),
    (r"\bкидків протидії Мудрості\b", "кидків протидії мудрістю"),
    (r"\bкидків протидії Харизми\b", "кидків протидії харизмою"),
    (r"\bкидках протидії Сили\b", "кидках протидії силою"),
    (r"\bкидках протидії Спритності\b", "кидках протидії спритністю"),
    (r"\bкидках протидії Статури\b", "кидках протидії статурою"),
    (r"\bкидках протидії Інтелекту\b", "кидках протидії інтелектом"),
    (r"\bкидках протидії Мудрості\b", "кидках протидії мудрістю"),
    (r"\bкидках протидії Харизми\b", "кидках протидії харизмою"),
    (r"\bкидок протидії Статура\b", "кидок протидії статурою"),
    (r"\bінтелектуальний кидок протидії\b", "кидок протидії інтелектом"),
    (r"\bкидок Сили\b", "кидок протидії силою"),
    (r"\bкидок Спритності\b", "кидок протидії спритністю"),
    (r"\bкидок Статури\b", "кидок протидії статурою"),
    (r"\bкидок Інтелекту\b", "кидок протидії інтелектом"),
    (r"\bкидок Мудрості\b", "кидок протидії мудрістю"),
    (r"\bкидок Харизми\b", "кидок протидії харизмою"),
    (r"\bподвигами\b", "рисами"),
    (r"\bподвигів\b", "рис"),
    (r"\bподвиги\b", "риси"),
    (r"\bподвигом\b", "рисою"),
    (r"\bподвигу\b", "риси"),
    (r"\bподвиг\b", "риса"),
    (r"\bслотами (?:для )?заклять\b", "чарунками заклять"),
    (r"\bслотів (?:для )?заклять\b", "чарунок заклять"),
    (r"\bслоти (?:для )?заклять\b", "чарунки заклять"),
    (r"\bслотом (?:для )?заклять\b", "чарункою заклять"),
    (r"\bслота (?:для )?заклять\b", "чарунки заклять"),
    (r"\bслоту (?:для )?заклять\b", "чарунці заклять"),
    (r"\bслоті (?:для )?заклять\b", "чарунці заклять"),
    (r"\bслот (?:для )?заклять\b", "чарунка заклять"),
    (r"\bгніздами заклять\b", "чарунками заклять"),
    (r"\bгнізд заклять\b", "чарунок заклять"),
    (r"\bгнізда заклять\b", "чарунки заклять"),
    (r"\bгніздом заклять\b", "чарункою заклять"),
    (r"\bгніздо заклять\b", "чарунка заклять"),
    (r"\bкомірками (?:для )?заклять\b", "чарунками заклять"),
    (r"\bкомірок (?:для )?заклять\b", "чарунок заклять"),
    (r"\bкомірки (?:для )?заклять\b", "чарунки заклять"),
    (r"\bкомірку (?:для )?заклять\b", "чарунку заклять"),
    (r"\bкомірка (?:для )?заклять\b", "чарунка заклять"),
    (r"\bатаки можливостей\b", "принагідні атаки"),
    (r"\bатак можливостей\b", "принагідних атак"),
    (r"\bатаками можливостей\b", "принагідними атаками"),
    (r"\bатака можливості\b", "принагідна атака"),
    (r"\bочк(?:и|ів|ами) чарівництва\b", "очки чародійства"),
    (r"\bвикористати чарунка\b", "використати чарунку"),
    (r"\bвитратити чарунка\b", "витратити чарунку"),
    (r"\bза допомогою чарунка\b", "за допомогою чарунки"),
    (r"\bрівень чарунка\b", "рівень чарунки"),
    (r"\bстан [«\"]?Лижна[»\"]?\b", "стан Повалення"),
    (r"\bстан [«\"]?Лежачи[»\"]?\b", "стан Повалення"),
    (r"\bЛижна\b", "Повалення"),
    (r"\bЛежачи\b", "Повалення"),
    (r"\bлежачи\b", "повалення"),
    (r"\bстан Невидимка\b", "стан Невидимості"),
    (r"\bНедоліками\b", "Завадами"),
    (r"\bНедоліків\b", "Завад"),
    (r"\bНедоліки\b", "Завади"),
    (r"\bНедоліком\b", "Завадою"),
    (r"\bнедоліком\b", "завадою"),
    (r"\bнедоліку\b", "завади"),
    (r"\bнедоліки\b", "завади"),
    (r"\bНедолік\b", "Завада"),
    (r"\bнедолік\b", "завада"),
    (r"\bреакцією\b", "реагуванням"),
    (r"\bреакцію\b", "реагування"),
    (r"\bреакції\b", "реагування"),
    (r"\bреакція\b", "реагування"),
    (r"\bтривалого відпочинку\b", "довгого відпочинку"),
    (r"\bтривалий відпочинок\b", "довгий відпочинок"),
    (r"\bзаклинаннях\b", "закляттях"),
    (r"\bзаклинаннями\b", "закляттями"),
    (r"\bзаклинань\b", "заклять"),
    (r"\bзаклинання\b", "закляття"),
    (r"\bзаклинателем\b", "заклиначем"),
    (r"\bзаклинателів\b", "заклиначів"),
    (r"\bзаклинателю\b", "заклиначеві"),
    (r"\bзаклинателя\b", "заклинача"),
    (r"\bзаклинатель\b", "заклинач"),
    (r"\bзаклинателями\b", "заклиначами"),
    (r"\bконтрзаклинання\b", "контрзакляття"),
    (r"\bкидками економії\b", "кидками протидії"),
    (r"\bкидків економії\b", "кидків протидії"),
    (r"\bкидки економії\b", "кидки протидії"),
    (r"\bкидком економії\b", "кидком протидії"),
    (r"\bкидок економії\b", "кидок протидії"),
    (r"\bкидками збереження\b", "кидками протидії"),
    (r"\bкидків збереження\b", "кидків протидії"),
    (r"\bкидки збереження\b", "кидки протидії"),
    (r"\bкидком збереження\b", "кидком протидії"),
    (r"\bкидок збереження\b", "кидок протидії"),
    (r"\bсвященнослужителями\b", "кліриками"),
    (r"\bсвященнослужителів\b", "кліриків"),
    (r"\bсвященнослужителях\b", "кліриках"),
    (r"\bсвященнослужителем\b", "кліриком"),
    (r"\bсвященнослужителю\b", "клірику"),
    (r"\bсвященнослужителя\b", "клірика"),
    (r"\bсвященнослужителі\b", "клірики"),
    (r"\bсвященнослужитель\b", "клірик"),
    (r"\bчорнокнижниками\b", "чаклунами"),
    (r"\bчорнокнижників\b", "чаклунів"),
    (r"\bчорнокнижниках\b", "чаклунах"),
    (r"\bчорнокнижником\b", "чаклуном"),
    (r"\bчорнокнижнику\b", "чаклунові"),
    (r"\bчорнокнижника\b", "чаклуна"),
    (r"\bчорнокнижники\b", "чаклуни"),
    (r"\bчорнокнижник\b", "чаклун"),
    (r"\bрозбійниками\b", "пройдисвітами"),
    (r"\bрозбійників\b", "пройдисвітів"),
    (r"\bрозбійником\b", "пройдисвітом"),
    (r"\bрозбійнику\b", "пройдисвітові"),
    (r"\bрозбійника\b", "пройдисвіта"),
    (r"\bрозбійники\b", "пройдисвіти"),
    (r"\bрозбійник\b", "пройдисвіт"),
    (r"\bточками фокусування\b", "очками зосередження"),
    (r"\bточок фокусування\b", "очок зосередження"),
    (r"\bточки фокусування\b", "очки зосередження"),
    (r"\bточку фокусування\b", "очко зосередження"),
    (r"\bточка фокусування\b", "очко зосередження"),
    (r"\bфункціями\b", "особливостями"),
    (r"\bфункцій\b", "особливостей"),
    (r"\bфункції\b", "особливості"),
    (r"\bфункцією\b", "особливістю"),
    (r"\bфункцію\b", "особливість"),
    (r"\bфункція\b", "особливість"),
    (r"\bрадіантними\b", "променевими"),
    (r"\bрадіантних\b", "променевих"),
    (r"\bрадіантною\b", "променевою"),
    (r"\bрадіантної\b", "променевої"),
    (r"\bрадіантну\b", "променеву"),
    (r"\bрадіантна\b", "променева"),
    (r"\bсяючими\b", "променевими"),
    (r"\bсяючих\b", "променевих"),
    (r"\bсяючою\b", "променевою"),
    (r"\bсяючої\b", "променевої"),
    (r"\bсяючу\b", "променеву"),
    (r"\bсяюча\b", "променева"),
    (r"\bколючими\b", "колольними"),
    (r"\bколючих\b", "колольних"),
    (r"\bколючою\b", "колольною"),
    (r"\bколючої\b", "колольної"),
    (r"\bколючу\b", "колольну"),
    (r"\bколюча\b", "колольна"),
    (r"\bкастингу\b", "проказування"),
    (r"\bкастинг\b", "проказування"),
    (r"\bриса Походження\b", "Риса походження"),
    (r"^риса:", "Риса:"),
    (r"натхнення(?=(?:за|і|змін|плюс))", "натхнення "),
)


def official_maps(target_text: str) -> tuple[dict[str, str], dict[str, str]]:
    en_nodes = ET.parse(BG_EN).getroot().findall("content")
    uk_nodes = ET.parse(BG_UK).getroot().findall("content")
    en_by_uid = {node.attrib["contentuid"]: node.text or "" for node in en_nodes}
    candidates: dict[str, collections.Counter[str]] = collections.defaultdict(collections.Counter)
    for node in uk_nodes:
        source = en_by_uid.get(node.attrib["contentuid"], "")
        target = node.text or ""
        if source and target:
            candidates[source][target] += 1

    target_lower = target_text.lower()
    result: dict[str, str] = {}
    exact: dict[str, str] = {}
    for source, targets in candidates.items():
        target = targets.most_common(1)[0][0]
        if (
            len(source) <= 120
            and "\n" not in source
            and "<" not in source
            and "[" not in source
            and "<" not in target
            and "[" not in target
            and CYRILLIC_RE.search(target)
        ):
            exact[source] = target
        words = re.findall(r"[A-Za-z][A-Za-z'’-]*", source)
        if (
            len(words) < 2
            or len(words) > 8
            or len(source) > 90
            or "\n" in source
            or "<" in source
            or "[" in source
            or not LATIN_RE.search(source)
            or source.lower() not in target_lower
        ):
            continue
        if len(targets) == 1 and CYRILLIC_RE.search(target) and "<" not in target and "[" not in target:
            result[source] = target
    return result, exact


def official_full_exact() -> dict[str, str]:
    """Map byte-for-byte English BG3 strings to their shipped Ukrainian text."""
    en_nodes = ET.parse(BG_EN).getroot().findall("content")
    uk_nodes = ET.parse(BG_UK).getroot().findall("content")
    en_by_uid = {node.attrib["contentuid"]: node.text or "" for node in en_nodes}
    candidates: dict[str, collections.Counter[str]] = collections.defaultdict(collections.Counter)
    for node in uk_nodes:
        source = en_by_uid.get(node.attrib["contentuid"], "")
        target = node.text or ""
        visible_target = TAG_SPLIT_RE.sub("", target)
        if source and target and CYRILLIC_RE.search(visible_target):
            candidates[source][target] += 1
    return {source: targets.most_common(1)[0][0] for source, targets in candidates.items()}


def replace_phrase(text: str, source: str, target: str) -> str:
    left = r"(?<![A-Za-z])" if source[:1].isalnum() else ""
    right = r"(?![A-Za-z])" if source[-1:].isalnum() else ""
    return re.sub(left + re.escape(source) + right, target, text, flags=re.IGNORECASE)


def refine_visible(text: str, replacements: list[tuple[str, str]]) -> str:
    parts = TAG_SPLIT_RE.split(text)
    for index in range(0, len(parts), 2):
        visible = parts[index]
        for source, target in replacements:
            if source.lower() in visible.lower():
                visible = replace_phrase(visible, source, target)
        for pattern, target in POSTPROCESS:
            visible = re.sub(pattern, target, visible, flags=re.IGNORECASE)
        parts[index] = visible
    return "".join(parts)


def normalize_source_terms(source: str, target: str) -> str:
    """Resolve Ukrainian homonyms only when the English source proves the game term."""
    if re.search(r"\bBonus Action(?:s)?\b", source, flags=re.IGNORECASE):
        for pattern, replacement in (
            (r"\bдодатковими діями\b", "вторинними діями"),
            (r"\bдодаткових дій\b", "вторинних дій"),
            (r"\bдодаткові дії\b", "вторинні дії"),
            (r"\bдодатковою дією\b", "вторинною дією"),
            (r"\bдодаткової дії\b", "вторинної дії"),
            (r"\bдодаткову дію\b", "вторинну дію"),
            (r"\bдодаткова дія\b", "вторинна дія"),
        ):
            target = re.sub(pattern, replacement, target, flags=re.IGNORECASE)
    if re.search(r"\bOpportunity Attack(?:s)?\b", source, flags=re.IGNORECASE):
        target = re.sub(
            r"\bатакувати цю істоту можливістю\b",
            "здійснити принагідну атаку проти цієї істоти",
            target,
            flags=re.IGNORECASE,
        )
        target = re.sub(r"\bатака можливістю\b", "принагідна атака", target, flags=re.IGNORECASE)
    if (
        re.search(r"\bSorcerer(?:s)?\b", source, flags=re.IGNORECASE)
        and not re.search(r"\bWizard(?:s)?\b", source, flags=re.IGNORECASE)
    ):
        for pattern, replacement in (
            (r"\bЧарівниками\b", "Чародіями"),
            (r"\bЧарівників\b", "Чародіїв"),
            (r"\bЧарівники\b", "Чародії"),
            (r"\bЧарівником\b", "Чародієм"),
            (r"\bЧарівникові\b", "Чародієві"),
            (r"\bЧарівника\b", "Чародія"),
            (r"\bЧарівник\b", "Чародій"),
            (r"\bчарівниками\b", "чародіями"),
            (r"\bчарівників\b", "чародіїв"),
            (r"\bчарівники\b", "чародії"),
            (r"\bчарівником\b", "чародієм"),
            (r"\bчарівникові\b", "чародієві"),
            (r"\bчарівника\b", "чародія"),
            (r"\bчарівник\b", "чародій"),
        ):
            target = re.sub(pattern, replacement, target)
    if re.search(r"\bArtificer(?:s)?\b", source, flags=re.IGNORECASE):
        for pattern, replacement in (
            (r"\bРемісниками\b", "Винахідниками"),
            (r"\bРемісників\b", "Винахідників"),
            (r"\bРемісники\b", "Винахідники"),
            (r"\bРемісником\b", "Винахідником"),
            (r"\bРемісникові\b", "Винахідникові"),
            (r"\bРемісника\b", "Винахідника"),
            (r"\bРемісник\b", "Винахідник"),
            (r"\bремісниками\b", "винахідниками"),
            (r"\bремісників\b", "винахідників"),
            (r"\bремісники\b", "винахідники"),
            (r"\bремісником\b", "винахідником"),
            (r"\bремісникові\b", "винахідникові"),
            (r"\bремісника\b", "винахідника"),
            (r"\bремісник\b", "винахідник"),
            (r"\bзаклять ремесла\b", "заклять винахідника"),
            (r"\bзакляття ремесла\b", "закляття винахідника"),
        ):
            target = re.sub(pattern, replacement, target)
    if re.search(r"\bProficiency Bonus\b", source, flags=re.IGNORECASE):
        target = re.sub(
            r"\bбонус(?:ом|у|а)? (?:за|до) майстерн(?:ість|ості)\b",
            lambda match: {
                "бонусом": "бонусом спеціалізації",
                "бонусу": "бонусу спеціалізації",
                "бонуса": "бонусу спеціалізації",
            }.get(match.group(0).split()[0].lower(), "бонус спеціалізації"),
            target,
            flags=re.IGNORECASE,
        )
    if re.search(r"\bSneak Attack(?:s)?\b", source, flags=re.IGNORECASE):
        for pattern, replacement in (
            (r"\b(?:прихованої|скритої) атаки\b", "підступного удару"),
            (r"\b(?:приховану|скриту) атаку\b", "підступний удар"),
            (r"\b(?:прихована|скрита) атака\b", "підступний удар"),
        ):
            target = re.sub(pattern, replacement, target, flags=re.IGNORECASE)
    if re.search(r"\bStrength\b", source, flags=re.IGNORECASE):
        target = re.sub(r"\bміцності\b", "сили", target, flags=re.IGNORECASE)
        target = re.sub(r"\bміцність\b", "сила", target, flags=re.IGNORECASE)
    return target


def prefixed_title(source: str, exact: dict[str, str], current_exact: dict[str, str]) -> str | None:
    def translate_suffix(value: str) -> str | None:
        folded_proofreading = {key.casefold(): item for key, item in PROOFREADING_EXACT_OVERRIDES.items()}
        folded_exact = {key.casefold(): item for key, item in exact.items()}
        folded_current = {key.casefold(): item for key, item in current_exact.items()}

        def lookup(item: str) -> str | None:
            return (
                # Reuse the localized base title first.  This keeps derived
                # titles (especially scrolls) identical to the actual spell
                # title instead of choosing an older synonym.
                current_exact.get(item)
                or exact.get(item)
                or PROOFREADING_EXACT_OVERRIDES.get(item)
                or EXACT_OVERRIDES.get(item)
                or MANUAL_PHRASES.get(item)
                or folded_current.get(item.casefold())
                or folded_exact.get(item.casefold())
                or folded_proofreading.get(item.casefold())
            )

        parts = value.split(": ")
        if len(parts) > 1:
            translated_parts = [lookup(part) for part in parts]
            if all(translated_parts):
                return ": ".join(translated_parts)  # type: ignore[arg-type]
        return lookup(value)

    match = re.fullmatch(r"Scroll of (.+)", source, flags=re.IGNORECASE)
    if match:
        translated = translate_suffix(match.group(1))
        if translated:
            return f'Сувій "{translated}"'

    match = re.fullmatch(r"(Fey Magic|Fey Touched): (.+)", source)
    if match:
        visible_suffix = re.sub(r"</?[^>]+>", "", match.group(2))
        translated = translate_suffix(visible_suffix)
        if translated:
            opening = re.match(r"(<[^>]+>)", match.group(2))
            closing = re.search(r"(</[^>]+>)$", match.group(2))
            if opening and closing:
                translated = f"{opening.group(1)}{translated}{closing.group(1)}"
            family = "Фейська магія" if match.group(1) == "Fey Magic" else "Торкнутий феями"
            return f"{family}: {translated}"

    match = re.fullmatch(r"Level (\d+): (.+) \(Lessons of the First Ones\)", source)
    if match:
        translated = translate_suffix(match.group(2))
        if translated:
            return f"Рівень {match.group(1)}: {translated} (Уроки найперших)"

    match = re.fullmatch(r"Level (\d+): (.+)", source)
    if match:
        suffix = match.group(2)
        translated = translate_suffix(suffix)
        if translated:
            return f"Рівень {match.group(1)}: {translated}"

    match = re.fullmatch(r"Feat: (.+)", source)
    if match:
        suffix = match.group(1)
        translated = translate_suffix(suffix)
        if translated:
            return f"Риса: {translated}"

    match = re.fullmatch(r"Magic Initiate: (.+)", source)
    if match:
        suffix = match.group(1)
        translated = translate_suffix(suffix)
        if translated:
            return f"Магічний хист: {translated}"

    match = re.fullmatch(r"Usable Classes: (.+)", source)
    if match:
        class_names = {
            "Artificer": "винахідник",
            "Barbarian": "варвар",
            "Bard": "бард",
            "Cleric": "клірик",
            "Druid": "друїд",
            "Fighter": "боєць",
            "Illrigger": "ілріґер",
            "Monk": "монах",
            "Paladin": "паладин",
            "Ranger": "слідопит",
            "Rogue": "пройдисвіт",
            "Sorcerer": "чародій",
            "Warlock": "чаклун",
            "Wizard": "чарівник",
        }
        classes = [part.strip() for part in match.group(1).split(",")]
        if all(name in class_names for name in classes):
            return "Доступні класи: " + ", ".join(class_names[name] for name in classes)
    return None


def main() -> None:
    source_nodes = ET.parse(SOURCE).getroot().findall("content")
    source_by_uid = {node.attrib["contentuid"]: node.text or "" for node in source_nodes}
    tree = ET.parse(TARGET)
    target_by_source: dict[str, collections.Counter[str]] = collections.defaultdict(collections.Counter)
    for node in tree.getroot().findall("content"):
        source = source_by_uid[node.attrib["contentuid"]]
        target_by_source[source][node.text or ""] += 1
    current_exact = {
        source: targets.most_common(1)[0][0]
        for source, targets in target_by_source.items()
        if source and targets
    }
    all_target_text = "\n".join(node.text or "" for node in tree.getroot().findall("content"))
    official, official_exact = official_maps(all_target_text)
    full_official_exact = official_full_exact()

    combined = dict(official)
    combined.update(MANUAL_PHRASES)
    replacements = sorted(combined.items(), key=lambda item: len(item[0]), reverse=True)

    changed = 0
    overridden = 0
    official_restored = 0
    for node in tree.getroot().findall("content"):
        uid = node.attrib["contentuid"]
        source = source_by_uid[node.attrib["contentuid"]]
        before = node.text or ""
        if uid in PROOFREADING_UID_OVERRIDES:
            after = PROOFREADING_UID_OVERRIDES[uid]
            overridden += 1
        elif uid in EDITORIAL_UID_OVERRIDES:
            after = EDITORIAL_UID_OVERRIDES[uid]
            overridden += 1
        elif uid in UID_OVERRIDES:
            after = UID_OVERRIDES[uid]
            overridden += 1
        elif source.casefold().startswith("scroll of ") and (
            title := prefixed_title(source, full_official_exact, current_exact)
        ) is not None:
            # BG3's official Ukrainian scroll naming convention is
            # «Сувій "<spell title>"».  Apply it before the older exact
            # editorial layer so every added scroll follows the same convention.
            after = title
        elif source in full_official_exact:
            after = full_official_exact[source]
            official_restored += 1
        elif source in PROOFREADING_EXACT_OVERRIDES:
            after = PROOFREADING_EXACT_OVERRIDES[source]
            overridden += 1
        elif source in EDITORIAL_EXACT_OVERRIDES:
            after = EDITORIAL_EXACT_OVERRIDES[source]
            overridden += 1
        elif source in EXACT_OVERRIDES:
            after = EXACT_OVERRIDES[source]
            overridden += 1
        elif (title := prefixed_title(source, full_official_exact, current_exact)) is not None:
            after = title
        else:
            after = refine_visible(before, replacements)
        if source not in full_official_exact:
            after = normalize_source_terms(source, after)
        after = proofreading_normalize(after)
        if after != before:
            changed += 1
            node.text = after

    ET.indent(tree, space="  ")
    tree.write(TARGET, encoding="utf-8", xml_declaration=True, short_empty_elements=False)
    print(
        f"changed={changed} exact_overrides={overridden} "
        f"official_exact={official_restored} official_phrases={len(official)} "
        f"total_phrases={len(replacements)}"
    )


if __name__ == "__main__":
    main()
